name: Main CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        repos: [steveltn-https-portal, docker-compose, jwilder-nginx-proxy]

    steps:
    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest
    
    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}

    - uses: actions/checkout@v2

    - uses: actions/checkout@v2
      with:
        repository: satackey/${{ matrix.repos }}
        depth: 0
        path: repos/${{ matrix.repos }}

    - name: Login to Docker Hub
      run: |
        docker login -u satackey -p ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Generate Dockerfile
      run: |
        find ${{ matrix.repos }} -name "*.sh"  -type f -printf "%f\n" | xargs -I{} sh -c "cd repos/${{ matrix.repos }} && ${PWD}/${{ matrix.repos }}/{}"
        cd repos/${{ matrix.repos }}

    - name: Build and push Docker image
      run: |
        docker buildx build \
          --platform linux/arm/v7 \
          --output "type=image,push=false" \
          --file repos/${{ matrix.repos }}/$(cat ${{ matrix.repos }}/.build-dockerfile-name) \
          -t satackey/${{ matrix.repos }}:latest \
          --push \
          repos/${{ matrix.repos }}
